### ISSUE TITLE
I'm probably doing something wrong

### ISSUE THREAD

**Issue by GHogChi** [SecurityInsanity/sash#1]
**Do you want to request a *feature* or report a *bug*?**
Well - an issue.  

I want to say up front that I really like the idea of **sash**.  I put "modularize .bashrc" into google, not expecting to see anything at all -  and **sash** was the first result that showed. My particular issue is that I'm bringing a second developer on board on a Java/Maven project, and I want to share some specialized bash functions for running Maven outside of our IDE (Intellij IDEA), but not my entire .bashrc.

**What is the current behavior?**
I followed the directions - installed sash, created a category, then a subcategory, added code and comments per the instructions (although I was a bit confused by them - I thought two windows would open simultaneously) and saved it to a file with a .sh extension.  Then I tried the **sash show** command. It showed the the category and the subcategory but didn't display the code or comments from the subcategory script.  I navigated to the sash/plugins directory and everything was there including the script. (Minor cosmetic issue - the instruction comments about where to type remained in the file, but then I suppose the idea is that users never look at the script....)

**If the current behavior is a bug, please provide the steps to reproduce.**
Added another category and subcategory and got the same result. Here's the bash interaction:

[sash-show-issue.txt](https://github.com/SecurityInsanity/sash/files/4308359/sash-show-issue.txt)

**What is the expected behavior?**
The specified subcategory script will be displayed.
 
**Which versions of SASH, and which OS are affected by this issue? Did this work in previous versions of SASH?**
The OS is Windows 10. I'm running Git/Bash. 

Sash version is the current snapshot (i.e., unreleased). Last release was 1.3.0.

**Comment by Mythra** [comment]
Hey @GHogChi ,

Thanks for the report! I've honestly never used git bash, so I have a feeling the actual bug lies there.  As for the comments, although they appear in comments so the user has some idea what to type, we expect them to be removed (which is why they're comments so that way incase they aren't removed they don't affect execution). But yes I agree it's unideal.

Looking through this. This actually seems to be a difference in setup with Windows vs Linux. Specifically windows doesn't have the executable file bit that says "This file is executable". Sash _currently_ enforces this bit be set (and adds it to any files it creates), so that way say an arbitrary file write vulnerability can't be escalated to full code execution with sash (if sash just loaded everything without checking that bit).

However, since windows doesn't have this concept of an executable bit it always reports this as false (if you notice, the things in your bashrc aren't actually being sourced at all).

I'll push up a commit that will allow you to set a particular setting to _not check_ for the executable bit, and then everything should work for windows.

**Comment by Mythra** [comment]
Hey @GHogChi ,

Can you checkout the latest patch of sash? It should contain a fix for git bash. At least it seems to work on my windows machine. There's actually no need to set any option, if we detect your running windows we won't check for the executable bit since there's no executable bit (or anything close to the same idea).

(Also as a note if you see an error message about how it can't find in files in `~/.bash/plugins/post/*.sh` you can just run: `  echo "# Kept so certain bash shells don't error out when no files in post directory." > "$HOME/.bash/plugins/post/keep.sh"`. Or you can blow away the entire `~/.bash/plugins` directory (starting sash again), and let setup do it for you)

**Comment by GHogChi** [comment]
Cynthia,

Thanks for your quick response!

I have hated Windows with a Mac&Linux passion for years, but as a
contractor I have to use the laptop my client gives me.  I'm all Linux at
home (gave my MBP to my wife after I blew her MBP's motherboard away trying
to install an SSD with inadequate static protection), so I'm going to
install sash on Linux first to get familiar with it, then come back to
Windows and try again per your suggestions.

Tom

**Comment by Mythra** [comment]
Sounds Good! I’m going to close this issue for now since it’s working on my windows machine. Feel free to reopen if minigw still isn’t working for you, or open a new issue if a new issue comes up.

Thanks,
Cynthia

**Comment by GHogChi** [comment]
So I can conclude the execute bit patch works under CygWin?  I'll try it
again soon just to see if there are any other problems with Git/Stash.

Keep up the good work!

**Comment by GHogChi** [comment]
I mean Git/Bash - Git/Stash is a different can of worms.

**Comment by Mythra** [comment]
I haven’t tested with Cygwin, but it should work detect (and work) with both Cygwin, and Git Bash as of the latest patches.

**Comment by GHogChi** [comment]
You said it worked for you on Windows, so I assumed you meant CygWin, since
you don't use Git/Bash. Is there a third Bash implementation on Windows?

**Comment by Mythra** [comment]
No I've tested it with Git/Bash on my windows machine. I hadn't tested it before this issue popped up, but it seems to be working now.

**Comment by GHogChi** [comment]
Okay - thanks. Sorry to bother you again.

**Comment by Mythra** [comment]
No need to be sorry at all!
